- src/mindmap-view.ts
- src/settings-tab.ts
- src/settings.ts
> Feat: all branches have the same color

- src/main.ts
- src/settings-tab.ts
- src/settings.ts
> fix: change slider to input

- .prettierrc
- package.json
- src/copy-image.ts
- src/html-escape-plugin.ts
- src/main.ts
- src/markmap-svg.ts
- src/mindmap-view.ts
- src/settings-tab.ts
- src/updater.ts
- yarn.lock
Rewrite pretty much the entire script and understood how it works so that it keeps all the animations. In last case I reimplement using React. 
I seems it is faster now. But it still has no animations. Which I think would be the ideal result.
> Rewrite: to run smoothly

- .gitignore
- src/copy-image.ts
- src/main.ts
- src/mindmap-view.ts
- src/settings-tab.ts
- src/settings.ts
Screenshot background changer.
issue #23
> Fix screenshot

- src/mindmap-view.ts
> feat: read frontmatter settings

- package.json
- src/copy-image.ts
- src/mindmap-view.ts
- yarn.lock
**Issue:** #23 ([link](https://github.com/AdrianSimionov/obsidian-mindmap-nextgen/issues/23))
Implementation of copying to clipboard with high quality output.
1. Run the plugin
2. Open a markdown document
3. Run the plugin
4. Click on actions on markmap leaf
5. Click on "Copy to clipboard"
6. Paste on any software or website that accepts image, such as [WhatsApp Web](https://web.whatsapp.com/), [imgbb](https://imgbb.com/) or [GIMP](https://www.gimp.org/downloads/).
> feat: copy image to clipboard

- README.md
- src/@types/models.d.ts
- src/inline-renderer.ts
- src/main.ts
- src/mindmap-view.ts
- src/settings-tab.ts
- src/settings.ts
What was done?
* Added borders and different background that can be turned on and off to inline markmap
> Feat: add inline markmap highlight

- README.md
- src/@types/screenshot.d.ts
- src/@types/screenshot.ts
- src/copy-image.ts
- src/main.ts
- src/settings-tab.ts
- src/settings.ts
**What was done?**
The settings tag, changed to drop down to reduce complexity around so many options.
**How to test it?**
If the result is as wanted.
> PNG Screenshot background to current theme

- src/inline-renderer.ts
- src/main.ts
- src/markmap-svg.ts
- src/mindmap-view.ts
- src/plugins/checkbox.ts
- styles.css
> Requested changes before submission to Obsidian Releases

- src/mindmap-view.ts
> Fix: Pin icon in wrong position, doesn't do anything

- src/mindmap-view.ts
> Fix: #80. No unpin option

- README.md
- src/@types/models.d.ts
- src/@types/settings.d.ts
- src/copy-image.ts
- src/inline-renderer.ts
- src/main.ts
- src/mindmap-view.ts
- src/settings-tab.ts
> Add screenshot background color to front-matter options

- src/settings-tab.ts
> fix(settings-tab): fix background style showing wrong option on render

- src/main.ts
- src/settings-tab.ts
Resolves #91.
Also groups settings under a "Coloring approach" heading
> feat: colour freeze level hidden unless using branch colouring

- src/copy-image.ts
- src/mindmap-view.ts
- src/settings-tab.ts
> fix: single colour mode not working

- src/views/register-events.ts
- src/views/view-manager.ts
> feat: update colors when settings change

- src/views/view.ts
Single-character pull request!
Closes #99
> fix: code blocks crash render if more than one

- src/filesystem.test.ts
- src/filesystem.ts
- src/inline-renderer.ts
- src/markmap-svg.ts
- src/settings-tab.ts
- src/types/obsidian.d.ts
- src/views/register-events.ts
- src/views/view-manager.ts
- src/views/view.ts
This solves #30.
Needs testing and tidying up.
> feat: can use the theme font or default

- README.md
> docs: explain markmap settings section

- src/rendering/screenshot.ts
- src/rendering/view-renderer.ts
- src/types/d3SvgToPng.d.ts
- src/views/view.ts
- styles.css
- tsconfig.json
Take screenshot and toggle toolbar items in the "More options" menu had stopped working.
> fix: take screenshot, toggle toolbar

- src/rendering/screenshot.ts
> feat: screenshot size scales with size of mindmap

- src/plugins/checkbox.ts
Fixes @zcysxy's bug in #136.
Probably resolves the issue. Will need feedback from @Titanfinger
> fix: crash when checkbox followed by link

- styles.css
> fix: improve display of inline mindmap on some themes

- src/rendering/renderer-inline.ts
> fix: dont reformat frontmatter on file open

- styles.css
> fix: nodes clipped in inline mindmaps

- babel.config.js
- package.json
- src/markmap-plugins/checkbox.test.ts
- src/markmap-plugins/checkbox.ts
- src/markmap-plugins/html-escape.test.ts
- src/markmap-plugins/html-escape.ts
add tests for markmap plugins (html escape, checkbox)
> test markmap plugins

- README.md
- package.json
- **chore: remove jest key from package.json**
- **docs: add 'buy me a coffee' link to readme**
> add buy me a coffee link to readme
